name: js-client-test
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
    steps:
      - uses: actions/checkout@v4
      - name: test
        run: |
          docker run --rm --tty --volume $PWD/js-client:/app node:20 bash -c 'cd /app; npm install && node --test mfn-client.test.js'
